// Do not edit this file manually
import { parseBlockSchema } from "@typebot.io/forge";
import { hostActionBlock, userAccessCheckBlock } from ".";

export const hostActionBlockSchema = parseBlockSchema(hostActionBlock);
export const userAccessCheckBlockSchema =
  parseBlockSchema(userAccessCheckBlock);
