// Do not edit this file manually
import { parseBlockSchema } from "@typebot.io/forge";
import { hostActionBlock, hostCapabilityCheckBlock } from ".";

export const hostActionBlockSchema = parseBlockSchema(hostActionBlock);
export const hostCapabilityCheckBlockSchema = parseBlockSchema(
  hostCapabilityCheckBlock,
);
